# Generated by Django 5.2 on 2025-06-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_lineitem_created_at_lineitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='line_item',
        ),
        migrations.AddField(
            model_name='shipment',
            name='line_item',
            field=models.ManyToManyField(related_name='shipments', to='store.lineitem'),
        ),
    ]
