# Generated by Django 5.2 on 2025-06-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_shipment_line_item_shipment_line_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='line_item',
            new_name='line_items',
        ),
    ]
